In [1]:
import requests
import gzip
import shutil
import pandas as pd
import json

In [2]:
proof_url = "https://prices.openfoodfacts.org/data/proofs.jsonl.gz"
data_path = "/Users/baslad01/data_dump/openfoodfacts"

image_prefix_url = "https://prices.openfoodfacts.org/img/"

# Download the file
r = requests.get(proof_url, stream=True)
with open(data_path + "proofs.jsonl.gz", "wb") as file:
    for chunk in r.iter_content(chunk_size=1024):
        file.write(chunk)


# Unzip the file
with gzip.open(data_path + "/proofs.jsonl.gz", 'rb') as f_in:
    with open(data_path + "/proofs.jsonl", 'wb') as f_out:
        shutil.copyfileobj(f_in, f_out)

In [3]:
# Read the file
df = pd.read_json(data_path + "/proofs.jsonl", lines=True)
df.head()

,id,location_id,file_path,mimetype,type,image_thumb_path,location_osm_id,location_osm_type,date,currency,receipt_price_count,receipt_price_total,price_count,owner,created,updated
0,7509,9.0,0008/xGpDk1mHT8.webp,image/webp,PRICE_TAG,0008/xGpDk1mHT8.400.webp,3.980570e+08,WAY,2024-06-19,EUR,NaN,NaN,4,bcd4e6,2024-06-26T10:25:04.124867Z,2024-06-26T10:26:35.355791Z
1,7546,559.0,0008/vpDU4wwsWA.jpg,image/jpeg,RECEIPT,0008/vpDU4wwsWA.400.jpg,2.299910e+09,NODE,2024-06-29,EUR,NaN,NaN,8,monsieurtanuki,2024-06-29T12:55:13.402154Z,2024-09-12T07:33:01.773998Z
2,7498,62.0,0008/wXE1kg1jLw.webp,image/webp,RECEIPT,0008/wXE1kg1jLw.400.webp,9.465674e+08,NODE,2024-06-24,EUR,NaN,NaN,2,bcd4e6,2024-06-24T18:53:32.816087Z,2024-06-24T18:54:24.836256Z
3,7331,378.0,0008/A9ooDKZL1M.webp,image/webp,PRICE_TAG,0008/A9ooDKZL1M.400.webp,6.029985e+09,NODE,2024-05-23,NOK,NaN,NaN,6,odinh,2024-06-13T19:04:22.119507Z,2024-09-11T21:29:27.448513Z
4,7501,585.0,0008/vqShR5M1f0.png,image/png,PRICE_TAG,0008/vqShR5M1f0.400.png,7.922998e+09,NODE,2024-06-25,EUR,NaN,NaN,2,demetra70,2024-06-25T08:13:52.255472Z,2024-06-25T08:16:40.109992Z

In [4]:
# Filter where type is PRICE_TAG
df = df[df["type"] == "PRICE_TAG"]
df.head()

,id,location_id,file_path,mimetype,type,image_thumb_path,location_osm_id,location_osm_type,date,currency,receipt_price_count,receipt_price_total,price_count,owner,created,updated
0,7509,9.0,0008/xGpDk1mHT8.webp,image/webp,PRICE_TAG,0008/xGpDk1mHT8.400.webp,3.980570e+08,WAY,2024-06-19,EUR,NaN,NaN,4,bcd4e6,2024-06-26T10:25:04.124867Z,2024-06-26T10:26:35.355791Z
3,7331,378.0,0008/A9ooDKZL1M.webp,image/webp,PRICE_TAG,0008/A9ooDKZL1M.400.webp,6.029985e+09,NODE,2024-05-23,NOK,NaN,NaN,6,odinh,2024-06-13T19:04:22.119507Z,2024-09-11T21:29:27.448513Z
4,7501,585.0,0008/vqShR5M1f0.png,image/png,PRICE_TAG,0008/vqShR5M1f0.400.png,7.922998e+09,NODE,2024-06-25,EUR,NaN,NaN,2,demetra70,2024-06-25T08:13:52.255472Z,2024-06-25T08:16:40.109992Z
5,7497,583.0,0008/I8wuhEcyQi.webp,image/webp,PRICE_TAG,0008/I8wuhEcyQi.400.webp,1.206895e+08,WAY,2024-06-24,CAD,NaN,NaN,1,mannvillian,2024-06-24T17:31:46.665855Z,2024-06-24T17:31:54.157169Z
11,7510,9.0,0008/yj22mIR9Nu.webp,image/webp,PRICE_TAG,0008/yj22mIR9Nu.400.webp,3.980570e+08,WAY,2024-06-19,EUR,NaN,NaN,4,bcd4e6,2024-06-26T10:27:01.792813Z,2024-06-26T10:31:11.126111Z

In [5]:
# Select a random sample of 1000 rows
df = df.sample(1000)
df.head()

,id,location_id,file_path,mimetype,type,image_thumb_path,location_osm_id,location_osm_type,date,currency,receipt_price_count,receipt_price_total,price_count,owner,created,updated
6668,1618,33.0,0002/vgRhXSVUUL.webp,image/webp,PRICE_TAG,0002/vgRhXSVUUL.400.webp,8.481801e+07,WAY,2024-01-20,EUR,NaN,NaN,1,jbieber,2024-01-20T11:17:19.044788Z,None
662,8266,776.0,0009/4IcTe48MQf.webp,image/webp,PRICE_TAG,0009/4IcTe48MQf.400.webp,1.702384e+09,NODE,2024-08-10,EUR,NaN,NaN,2,bcd4e6,2024-08-18T16:10:41.403341Z,2024-08-18T16:11:59.098693Z
2011,9322,378.0,0010/H6je0jKZ8b.webp,image/webp,PRICE_TAG,0010/H6je0jKZ8b.400.webp,6.029985e+09,NODE,2024-09-14,NOK,NaN,NaN,1,odinh,2024-09-26T21:47:15.732294Z,2024-09-26T21:47:15.736423Z
4873,11655,468.0,0014/M9b5WfASIt.jpg,image/jpeg,PRICE_TAG,0014/M9b5WfASIt.400.jpg,2.145268e+06,RELATION,2024-10-15,EUR,NaN,NaN,1,professordoc,2024-10-21T13:48:52.924377Z,2024-10-21T13:48:52.927032Z
8640,1972,8.0,0002/XvZQ67zkAO.webp,image/webp,PRICE_TAG,0002/XvZQ67zkAO.400.webp,3.980570e+08,WAY,2024-02-01,EUR,NaN,NaN,12,bcd4e6,2024-02-01T23:41:28.934882Z,None

In [6]:
# Extract the URLs from the DataFrame
urls = df['file_path'].tolist()
ids = df['id'].tolist()

# Format the URLs into the desired JSON structure
formatted_data = [{"id": id,"data": {"image_url": image_prefix_url + url}} for url, id in zip(urls, ids)]

# Export the JSON structure to a file
output_path = f'{data_path}/formatted_urls.json'
with open(output_path, 'w') as json_file:
    json.dump(formatted_data, json_file, indent=2)

print(f"Formatted data saved to {output_path}")

Formatted data saved to /Users/baslad01/data_dump/openfoodfacts/formatted_urls.json